// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BestJourneyDbContext))]
    [Migration("20240704134239_AddUsersAndJourneysSeed")]
    partial class AddUsersAndJourneysSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Domain.Journeys.Journey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Journeys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d543e25e-6341-4fa9-834f-36b6d2f1ea7f"),
                            City = "Istanbul",
                            Country = "Turkey",
                            CreatedAt = new DateTime(2024, 7, 4, 15, 42, 38, 574, DateTimeKind.Local).AddTicks(4732),
                            CreatorId = new Guid("88d43f6f-309d-4c8a-a95a-7ba3ec8f92da"),
                            Description = "Welcome to Istanbul! Visit and discover the history of the most beautiful city in the world",
                            IsActive = true,
                            Name = "Discover Istanbul",
                            Price = 650m
                        },
                        new
                        {
                            Id = new Guid("bbe9ad9a-d9dd-4025-9a2d-6c383e705364"),
                            City = "Alanya",
                            Country = "Turkey",
                            CreatedAt = new DateTime(2024, 7, 4, 15, 42, 38, 574, DateTimeKind.Local).AddTicks(4785),
                            CreatorId = new Guid("88d43f6f-309d-4c8a-a95a-7ba3ec8f92da"),
                            Description = "Welcome to Alanya! Visit and discover the different parts of this beatiful country from the beach to the forest without forgetting the ancient ruins.",
                            IsActive = true,
                            Name = "Travel to Alanya",
                            Price = 400m
                        });
                });

            modelBuilder.Entity("Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JourneyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParticipentCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteName")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email", "Role")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b9217759-7274-477b-8772-284803c86a34"),
                            CreatedAt = new DateTime(2024, 7, 4, 15, 42, 38, 574, DateTimeKind.Local).AddTicks(2692),
                            Email = "customer@example.com",
                            Firstname = "Tom",
                            Lastname = "Doe",
                            Password = "$2a$11$iSHHD/NUGOUdtgEOrcOyQu4TmMzfGVpXoRsLvtF0DMSVA5shlRvTu",
                            Phone = "0601010101",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("88d43f6f-309d-4c8a-a95a-7ba3ec8f92da"),
                            CompanyName = "Trivago",
                            CreatedAt = new DateTime(2024, 7, 4, 15, 42, 38, 574, DateTimeKind.Local).AddTicks(2806),
                            Email = "supplier@example.com",
                            Firstname = "John",
                            Lastname = "Doe",
                            Password = "$2a$11$iSHHD/NUGOUdtgEOrcOyQu4TmMzfGVpXoRsLvtF0DMSVA5shlRvTu",
                            Phone = "0602020202",
                            Role = 1,
                            WebsiteName = "Trivago.fr",
                            WebsiteUrl = "https://www.trivago.fr"
                        });
                });

            modelBuilder.Entity("Domain.Journeys.Journey", b =>
                {
                    b.HasOne("Domain.Users.User", "Creator")
                        .WithMany("Journeys")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Domain.Orders.Order", b =>
                {
                    b.HasOne("Domain.Journeys.Journey", "Journey")
                        .WithMany("Orders")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Users.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Journeys.Journey", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Navigation("Journeys");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
